django_kr/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing_app.urls', namespace='newsletter')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog_app.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_kr/django_kr/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django_kr/mailing_app/urls.py
from .apps import MailingAppConfig
from django.urls import path
from .views import HomeTemplateView, ClientListView, ClientUpdateView, ClientDeleteView, MessageCreateView, \
    MessageListView, MessageUpdateView, MessageDeleteView, LogListView, NewsLetterDeleteView, NewsLetterCreateView, \
    NewsLetterListView, NewsLetterUpdateView, ClientCreateView, status_newsletter, finish_newsletter, \
    ClientDetailView, MessageDetailView, NewsLetterDetailView
from users.views import UserListView

app_name = MailingAppConfig.name

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='base'),

    path('user_list', UserListView.as_view(), name='user_list'),

    path('client_create', ClientCreateView.as_view(), name='client_create'),
    path('client_list', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/edit/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    path('create_message', MessageCreateView.as_view(), name='create_message'),
    path('message_list', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('edit_message/<int:pk>', MessageUpdateView.as_view(), name='edit_message'),
    path('delete_message/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),

    path('create_mailing', NewsLetterCreateView.as_view(), name='create_mailing'),
    path('mailing_list', NewsLetterListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', NewsLetterDetailView.as_view(), name='mailing_detail'),
    path('edit_mailing/<int:pk>', NewsLetterUpdateView.as_view(), name='edit_mailing'),
    path('delete_mailing/<int:pk>', NewsLetterDeleteView.as_view(), name='delete_mailing'),

    path('status_mailing/<int:pk>', status_newsletter, name='status_mailing'),
    path('finish_mailing/<int:pk>', finish_newsletter, name='finish_mailing'),

    path('attempt_list', LogListView.as_view(), name='attempt_list'),
]

django_kr/users/urls.py
from django.urls import path
from .apps import UsersConfig
from .views import UserLoginView, UserLogoutView, UserUpdateView, generate_password, UserListView, \
    status_user, RegisterUserView, VerifyUserView

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('logout/', UserLogoutView.as_view(http_method_names=['get', 'post', 'options']), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('verify/', VerifyUserView.as_view(), name='verify'),

    path('profile/genpassword', generate_password, name='genpassword'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('status_user/<int:pk>', status_user, name='status_user'),
]

django_kr/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import random

random_code = ''.join(random.sample('0123456789', 6))
NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = models.CharField(max_length=50, default='default_username', verbose_name='Имя пользователя')

    email = models.EmailField(unique=True, verbose_name='Почта')
    phone = models.CharField(max_length=30, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=30, verbose_name='Страна', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', default='default user.png', verbose_name="Аватар", **NULLABLE)

    verify_code = models.CharField(max_length=6, default=random_code, verbose_name='Код верификации')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('can_block_users', 'Can activate or deactivate user')
            # Может блокировать пользователей сервиса (set is_active)
        ]

django_kr/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class RegisterForm(StyleFormMixin, UserCreationForm):
    """Форма регистрации"""

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):
    """Форма профиля пользователя"""

    class Meta:
        model = User
        fields = ('username', 'country', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        """Скрытие поля password"""
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class ListUserForm(StyleFormMixin, forms.ModelForm):
    """Форма модели User для списка"""
    pass
    # class Meta:
    #     model = User
    #     fields = ('email', 'phone', 'country', )


class VerifyForm(forms.Form):
    code = forms.CharField(max_length=4)

django_kr/users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.views.generic import CreateView, UpdateView, ListView, FormView
from .models import User
from .forms import RegisterForm, UserForm, ListUserForm, VerifyForm
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
import random
from config.settings import EMAIL_HOST_USER
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import logout


class UserLoginView(LoginView):
    template_name = 'users/login.html'


class UserLogoutView(LogoutView):
    def get(self, request):
        logout(request)
        return redirect('newsletter:base')


class RegisterUserView(SuccessMessageMixin, CreateView):
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('users:verify')
    template_name = 'users/register.html'

    def get_success_message(self, cleaned_data):
        return f'Вам на почту отправлен код. Введите его для завершения регистрации.'

    def form_valid(self, form):
        new_user = form.save(commit=False)
        code = ''.join(random.sample('0123456789', 4))
        new_user.verify_code = code
        new_user.is_active = False
        new_user.save()
        send_mail(
            'Верификация',
            f'Ваш код подтверждения: {code}',
            EMAIL_HOST_USER,  # замените на ваш EMAIL_HOST_USER
            [new_user.email],
            fail_silently=False,
        )
        self.request.session['user_id'] = new_user.id
        return super().form_valid(form)


class VerifyUserView(FormView):
    form_class = VerifyForm
    template_name = 'users/verify.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user_id = self.request.session.get('user_id')
        if not user_id:
            messages.error(self.request, 'Ошибка. Попробуйте зарегистрироваться заново.')
            return redirect('users:register')

        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            messages.error(self.request, 'Пользователь не найден.')
            return redirect('users:register')

        if user.verify_code == form.cleaned_data['code']:
            user.is_active = True
            user.verify_code = ''
            user.save()
            messages.success(self.request, 'Вы успешно подтвердили почту. Теперь вы можете войти.')
            return super().form_valid(form)
        else:
            messages.error(self.request, 'Неправильный код подтверждения.')
            return self.form_invalid(form)


# class RegisterUserView(SuccessMessageMixin, CreateView):
#     model = User
#     form_class = RegisterForm
#     success_url = reverse_lazy('users:login')
#     template_name = 'users/register.html'
#
#     def get_success_message(self, cleaned_data):
#         return f'Вам на почту отправлен код. Введите его для завершения регистрации'
#
#     def form_valid(self, form):
#         """Верификация по ссылке через почту"""
#         new_user = form.save()
#         code = ''.join(random.sample('0123456789', 4))
#         new_user.verify_code = code
#         new_user.is_active = False
#         send_mail(
#             'Верификация',
#             f'Перейдите по ссылке для верификации: '
#             f'http://127.0.0.1:8000/users/verification/{code}',
#             EMAIL_HOST_USER,
#             [new_user.email]
#         )
#         return super().form_valid(form)


# def verification(request, code):
#     """Контроллер подтверждения верификации"""
#     user = User.objects.get(verify_code=code)
#     user.is_active = True
#     user.save()
#     return redirect(reverse('users:login'))


# class ProfileView(UpdateView):
#     model = User
#     form_class = UserProfileForm
#     success_url = reverse_lazy('user:profile')
#     extra_context = {'title': 'Профиль'}
#
#     def get_object(self, queryset=None):
#         return self.request.user


class UserUpdateView(UpdateView):
    """Контроллер страницы профиля"""
    model = User
    form_class = UserForm
    success_url = reverse_lazy('newsletter:base')

    def get_object(self, queryset=None):
        """Отключаем необходимость получения pk, получая его из запроса"""
        return self.request.user


def generate_password(request):
    """Контроллер смены пароля и отправка сгенерированного пароля на почту"""
    new_password = User.objects.make_random_password()
    request.user.set_password(new_password)
    request.user.save()
    send_mail(
        'Смена пароля',
        f'Ваш новый пароль для авторизации: {new_password}',
        EMAIL_HOST_USER,
        [request.user.email]
    )
    messages.success(request,
                     'Вам на почту отправлено письмо '
                     'с новым паролем для вашего аккаунта')
    return redirect(reverse('users:login'))


class UserListView(LoginRequiredMixin, ListView):
    """Контроллер страницы списка пользователей"""
    model = User
    form_class = ListUserForm
    # permission_required = 'users.view_user'


@permission_required('users.can_block_users')
def status_user(request, pk):
    """Контроллер смены статуса пользователя"""
    user = User.objects.get(pk=pk)

    if not user.is_superuser:
        user.is_active = not user.is_active
        user.save()

    return redirect(reverse('users:user_list'))

django_kr/users/templates/users/base.html
{% load static %}
{% load my_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Website</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style>
        .navbar {
            margin-bottom: 20px;
        }
        .card {
            border: none;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            transition: transform 0.2s ease-in-out;
        }
        .card:hover {
            transform: scale(1.02);
        }
        .card-header {
            font-weight: bold;
        }
        .card-img-top {
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }
        .container {
            max-width: 1200px;
        }
    </style>
</head>

<body>
<div class="container">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'newsletter:base' %}">Website</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'newsletter:base' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog_app:blog_list' %}">Блог</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'newsletter:client_list' %}">Клиенты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'newsletter:user_list' %}">Пользователи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mailing_app:message_list' %}">Сообщения</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mailing_app:mailing_list' %}">Рассылки</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {% if user.is_authenticated %}
                        {{ user.username }}
                        {% else %}
                        Вход
                        {% endif %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
                        {% if user.is_superuser %}
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Админка</a>
                        {% endif %}
                        {% else %}
                        <a class="dropdown-item" href="{% url 'users:login' %}">Войти</a>
                        <a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>

<div class="container pt-5">
    <!-- Статистика -->
    {% if is_home %}
    <div class="row mb-4">
        <div class="col-md-3 mb-4">
            <div class="card text-center">
                <div class="card-header bg-info text-white">
                    Всего рассылок
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ newsletter_count }}</h5>
                </div>
            </div>
        </div>
        <div class="col-md-3 mb-4">
            <div class="card text-center">
                <div class="card-header bg-success text-white">
                    Активные рассылки
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ active_newsletter }}</h5>
                </div>
            </div>
        </div>
        <div class="col-md-3 mb-4">
            <div class="card text-center">
                <div class="card-header bg-primary text-white">
                    Клиенты
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ client_count }}</h5>
                </div>
            </div>
        </div>
    </div>
    <h2 class="mb-4">Наши блоги</h2>
    <div class="row">
        {% for blog in random_blogs %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img class="card-img-top" src="{{ blog.image|mymedia }}" alt="{{ blog.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ blog.title }}</h5>
                    <p class="card-text">{{ blog.content|truncatewords:20 }}</p>
                    <a href="{% url 'blog_app:blog_detail' blog.id %}" class="btn btn-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}
</div><!-- /.container -->

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

django_kr/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Войти
                    </button>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

django_kr/users/templates/users/register.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}

django_kr/users/templates/users/user_confirm_block.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<h1>Удаление сообщения: {{ user.username }}</h1>
<p>Вы уверены, что заблокировать пользователя?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Да, заблокировать</button>
    <a href="{% url 'users:user_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

django_kr/users/templates/users/user_form.html
{% extends 'users/base.html' %}
{% load my_tags %}
{% load static %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <img class="card-img-top"
                     src="{{ object.avatar|mymedia }}"
                >
                <div class="card-header">
                    <h3>
                        Профиль
                    </h3>
                    <h5>
                        {{ object.email }}
                    </h5>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Сохранить
                    </button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

django_kr/users/templates/users/user_list.html
{% extends 'mailing_app/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2 class="my-4">Список пользователей</h2>
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4 mb-4">
            <div class="card box-shadow">
                <div class="card-body {% if object.is_active %}bg-light{% else %}bg-danger text-white{% endif %}">
                    <h5 class="card-title">{{ object.username }}</h5>
                    <p class="card-text">{{ object.email }}</p>
                    <p class="card-text">
                        Статус:
                        {% if object.is_active %}
                        <span class="badge badge-success">Активен</span>
                        {% else %}
                        <span class="badge badge-secondary">Заблокирован</span>
                        {% endif %}
                    </p>
                    {% if user.is_authenticated and perms.users.can_block_users %}
                    {% if object != user and not object.is_superuser %}
                    <a href="{% url 'users:status_user' object.id %}" class="btn btn-sm btn-outline-primary">
                        {% if object.is_active %}
                        Заблокировать
                        {% else %}
                        Разблокировать
                        {% endif %}
                    </a>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

django_kr/users/templates/users/verify.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
<h2>Подтверждение почты</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Подтвердить</button>
</form>
{% endblock %}